language: python
python:
- 3.6.3
script:
- python test.py
deploy:  
  provider: heroku  
  app: myapp-ailsons 
  on:    
    branch: master
  api_key:
    secure: PFuTu8MKdy9+IB963JMr51D6mulhGjEE2aU31vNpp+HURydioPhcSzKTL3l5cIEieYXeeNo6pzkMx0UFugE2c64UfR6yz5IcSs2ju4wozoA2qqkpdoYk16YEmKrAB6/cRTsaHojgAVNcPyTMtmzjHDbkZWtG/8BFEmFMdvPwmHmjWhQi2F9Qkp3FDyp6BskuVRx/klSJ7sMaZz0Tc14kff3lDLfzQ5sG+aCBwzRAokR/dmPJj6HPerzHqXpnFipRl4L1o+jqJjXXdUDo4HmN8J3axP27BRC8fcqjeSssZTFXn0ihHUZ2FbncZrsSC4iXCKIKhJ2kgzW6PuJnACbPOvfJt0L1W6mY8yFuHmnl4mdjE6/3Wd/6xPbGO7j3ZjaFLlxerjDlIqpkbIuN65BdgHD0ebfnO97O3zJ4Qy+OMetnjRYGBCO9URy4hS4XMC0FuL35PLLfcsLon9ox1C9taSUOZyZJ4Qm+BJeBbKq7MbVeMDWWW7GciLwv4xUemF/2DwVm/9JHkFrij4UcGAzT9N4o5oB6lLGBRsdIRn6vflgiMCt6xNvlcFsbVuE/XeBq20zvdtPmwB7YoHjj55nPu8qUXnvr+etkNtDeRQEabASSEs5pC+cAVm7J4pyleUKwUdYC9yirnk2CwmmysyUkcP6XxFLByZT01C8hKQ7qq6Q=
